/*
 * Copyright (c) The One True Way 2021. Apache License 2.0. The authors accept no liability, 0 nada for the use of this software.  It is offered "As IS"  Have fun with it!!
 */

package bridgemodel

const REGISTRATION_AUTH_SUBJECT = "natssync.regauth.request"

//this is a generic message that will be encrypted and decrypted on the bridge.
//Its basicly the NATS data
type NatsMessage struct {
	Subject string
	Reply   string
	Data    []byte
}

type HttpReqHeader struct {
	Key    string
	Values []string
}
type K8SApiReqMessage struct {
	HttpMethod string
	HttpPath   string
	Body       []byte
	Headers    []HttpReqHeader
	Target     string
}
type K8SApiRespMessage struct {
	HttpStatusCode int
	RespBody       string
	RequestID      string
	Headers        map[string]string
}

type RegistrationRequest struct {
	//user and secret provided by the client
	AuthToken string `json:"authToken"`
	//for reference, this is generated by the bridge server
	LocationID string `json:"locationID"`
}
type RegistrationResponse struct {
	Success bool `json:"success"`
}
