
apiVersion: v1
kind: Pod

metadata:
  name: relaylet
  labels:
    type: relaylet
    role: relaylet
spec:
  serviceAccountName: relay-sa
  containers:
    - name: relaylet
      image: theotw/k8srelaylet:dev
      imagePullPolicy: Never
      env:
        - name: LOG_LEVEL
          value: trace
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: natssync-server-config
              key: nats_url
