apiVersion: v1
kind: PersistentVolume
metadata:
  name: misc-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/miscstuff"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miscstuff-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi