apiVersion: v1
kind: Service
metadata:
  name: sync-server
spec:
  type: NodePort
  selector:
    type: sync-server
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
      nodePort: 30080