apiVersion: apps/v1
kind: Deployment

metadata:
  name: sync-client

spec:
  template:
    metadata:
      name: sync-client
      labels:
        type: sync-client

    spec:
      containers:
        - name: sync-client
          image: theotw/natssync-client:latest
          imagePullPolicy: Never
          env:
            - name: LOG_LEVEL
              value: "trace"
            - name: NATS_SERVER_URL
              value: "nats://nats:4222"
            - name: CLOUD_BRIDGE_URL
              value: "http://sync-server.cloud.svc.cluster.local:7070"
            - name: PREM_ID
              value: "client1"
            - name: REDIS_URL
              value: "redis:6379"
            - name: KEYSTORE_URL
              value: "mongodb://mongo"

  replicas: 1

  selector:
    matchLabels:
      type: sync-client
