apiVersion: v1
kind: Service
metadata:
  name: sync-client
spec:
  type: NodePort
  selector:
    type: sync-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
