apiVersion: apps/v1
kind: Deployment

metadata:
  name: natssync-node

spec:
  template:
    metadata:
      name: natssyncserver-pod
      labels:
        type: natssync-server

    spec:
      containers:
        - name: natssync-server
          image: theotw/natssync-server
          ports:
            - containerPort: 8080
              hostPort: 8080
          env:
            - name: LOG_LEVEL
              value: "trace"
            - name: NATS_SERVER_URL
              value: "nats://nats:4222"
            - name: REDIS_URL
              value: "redis-cache-poc.tkxust.ng.0001.usw2.cache.amazonaws.com:6379"

  replicas: 1

  selector:
    matchLabels:
      type: natssync-server
