name: Client Echo Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: '*'

jobs:
  echotest:
    name: Dockerized Echo Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build Images
      run: |
        make allimages

    - name: Deploy Docker Containers
      run: single_cluster_test/docker-deploy.sh

    - name: Client Registration
      run: |
        go run apps/natstool.go -u nats://localhost:4222 -s natssync.registration.request -m '{"authToken":"42","locationID":"client1"}'
        sleep 1
        curl -X POST -H 'Content-Type: application/json' -d '{"authToken":"42","locationID":"client1"}' "http://localhost:8081/bridge-client/1/register" | jq .locationID | sed s/\"//g > locationID.txt
        echo "ID: `cat locationID.txt`"

    - name: Echo Test
      run: timeout 30 go run apps/echo_client.go -m "hello world" -i `cat locationID.txt`

    - name: Deploy to DockerHub
      if: github.ref == "refs/heads/main"
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        export IMAGE_REPO=theotw
        export IMAGE_TAG=$(date -u ‘+%Y%m%d%H%M’)
        allimagesBuildAndPush
        export IMAGE_TAG=latest
        allimagesBuildAndPush

    - name: Collect Logs
      if: always()
      run: single_cluster_test/docker-logs.sh logs

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs
        retention-days: 5
